name: Hello In C

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - uses: gekkowrldtest/helloworldinc@main

