name: Run Betty

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - name: Check Style
        run: |
          git clone https://github.com/alx-tools/Betty
          cd Betty
          sudo ./install.sh
          cd ..
          git clone https://github.com/${{ github.repository }} ${{ github.actor }}
          echo ${{ github.actor }}
          cd ${{ github.actor }}
          betty *
      - name: Dump Github context
        run: echo '${{ toJSON(github.event) }}' | jq
