name: Run Betty

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-style:
    name: Run Style
    runs-on: ubuntu-latest
    steps:
      - name: Build Betty
        run: |
          git clone https://github.com/alx-tools/Betty
          git clone ${{ github.repositoryUrl }} ${{ github.actor }}
          cd Betty
          sudo ./install.sh
          cd ${{ github.actor }}
          ls
