name: Run Betty

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-style:
    name: Run Style
    runs-on: ubuntu-latest
    steps:
      - name: List Folders
        run: 
          find . -type d -printf "%P\n"
      - name: Run style.sh
        run: |
          ls -aR . /home
          echo "Done"
