name: Run Betty

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-style:
    name: Run Style
    runs-on: ubuntu-latest
    steps:
      - name: Build Betty
        id: build-betty
        run: |
          git clone https://github.com/alx-tools/Betty
          cd Betty
          sudo ./install.sh
          cd ..
          git clone https://github.com/${{ github.repository }} ${{ github.actor }}
          echo ${{ github.actor }}
          cd ${{ github.actor }}
          betty *
